# Generated by Django 4.0.6 on 2022-07-30 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=614)),
                ('brand', models.CharField(max_length=256)),
                ('img_src', models.CharField(max_length=614)),
                ('slug', models.SlugField(blank=True, max_length=124)),
                ('category', models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('desktop-computers', 'Desktop-computers'), ('television', 'Television'), ('smart-tvs', 'Smart-tvs'), ('digital-cameras', 'Digital-cameras'), ('generators', 'Generators')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=614)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='category.product')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
