# Generated by Django 4.0.6 on 2022-08-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_product_price_product_title_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='properties',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
