# Generated by Django 4.0.6 on 2022-08-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_title_product_properties_remove_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_src',
            new_name='image',
        ),
    ]
