# Generated by Django 4.0.6 on 2022-08-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_product_name'),
        ('category', '0004_rename_img_src_product_image'),
    ]

    operations = [
    ]
