# Generated by Django 4.0.6 on 2022-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_merge_20220803_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_src',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='infinix', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ram_size',
            field=models.CharField(choices=[('2gb', '2GB'), ('4gb', '4GB'), ('6gb', '6GB'), ('8gb', '8GB')], default='4gb', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rom_size',
            field=models.CharField(choices=[('16gb', '16GB'), ('32gb', '32GB'), ('64gb', '64GB'), ('128gb', '128GB'), ('256gb', '256GB')], default=('4gb', '4GB'), max_length=5),
            preserve_default=False,
        ),
    ]
